version: '3.8'

services:
  # ── MySQL Databases (one per service) ──
  users-db:
    image: mysql:8.0
    container_name: users-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    volumes:
      - users_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog-db:
    image: mysql:8.0
    container_name: catalog-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: catalog_db
    ports:
      - "3307:3306"
    volumes:
      - catalog_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-db:
    image: mysql:8.0
    container_name: orders-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: orders_db
    ports:
      - "3308:3306"
    volumes:
      - orders_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  notifications-db:
    image: mysql:8.0
    container_name: notifications-db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: notifications_db
    ports:
      - "3309:3306"
    volumes:
      - notifications_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Redis (Cart + Distributed Locks) ──
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── Redis Commander (GUI) ──
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8090:8081"
    depends_on:
      - redis

  # ── LocalStack (SNS + SQS + SES) ──
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns,sqs,ses
      DEFAULT_REGION: ap-south-1
      DEBUG: 0
    volumes:
      - localstack_data:/var/lib/localstack
      - ./localstack-init.sh:/etc/localstack/init/ready.d/init.sh

volumes:
  users_data:
  catalog_data:
  orders_data:
  notifications_data:
  redis_data:
  localstack_data:
